#!/bin/bash
echo "=========================================="
echo "Database Schema Diagnostic"echo "=========================================="
echo ""
echo "=== HISTORY.DB SCHEMA ==="
docker exec mam-audiofinder sqlite3 /data/history.db ".schema history"
echo ""
echo "=== HISTORY.DB COLUMNS ==="
docker exec mam-audiofinder sqlite3 /data/history.db "PRAGMA table_info(history);"
echo ""
echo "=== COVERS.DB SCHEMA ==="docker exec mam-audiofinder sqlite3 /data/covers.db ".schema covers"
echo ""
echo "=== COVERS.DB COLUMNS ==="
docker exec mam-audiofinder sqlite3 /data/covers.db "PRAGMA table_info(covers);"
echo ""
echo "=== APPLIED MIGRATIONS (history.db) ==="
docker exec mam-audiofinder sqlite3 /data/history.db "SELECT * FROM applied_migrations ORDER BY applied_at DESC LIMIT 5;"
echo ""
echo "=== APPLIED MIGRATIONS (covers.db) ==="
docker exec mam-audiofinder sqlite3 /data/covers.db "SELECT * FROM applied_migrations ORDER BY applied_at DESC LIMIT 5;"
